# Generated by Django 2.2.7 on 2019-11-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_category_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='places', to='places.Category'),
        ),
        migrations.AddField(
            model_name='place',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='places', to='places.Comment'),
        ),
    ]
