# Generated by Django 2.2.7 on 2019-11-13 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0006_auto_20191113_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='name',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='friend',
            name='users',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
