# Generated by Django 2.2.7 on 2019-11-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20191113_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='places',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment', to='places.Place'),
        ),
    ]
