# Generated by Django 2.2.7 on 2019-11-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20191113_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='places',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='places.Place'),
        ),
    ]
