# Generated by Django 2.2.7 on 2019-11-13 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20191113_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='users',
            field=models.ManyToManyField(blank='True', related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
