# Generated by Django 2.2.7 on 2019-11-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20191114_0010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
