# Generated by Django 2.2.7 on 2019-11-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_auto_20191113_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
